// 满意度调查模块入口：管理调查问卷并查看极简结果报表。
import React, { useMemo, useState } from 'react';
import { BarChart3, Copy, Edit2, FileText, Plus, Search, Trash2 } from 'lucide-react';
import { BotConfiguration, SatisfactionSurvey } from '../../types';
import SatisfactionSurveyEditor from './SatisfactionSurveyEditor';
import SatisfactionSurveyReport from './SatisfactionSurveyReport';

interface Props { surveys: SatisfactionSurvey[]; onChange: (items: SatisfactionSurvey[]) => void; bots: BotConfiguration[]; onOpenCallRecord: (callId: string) => void; }
const statusMeta = { draft: ['草稿', 'bg-amber-50 text-amber-600'], published: ['已发布', 'bg-emerald-50 text-emerald-600'], disabled: ['已停用', 'bg-slate-100 text-slate-500'] } as const;

// 新建调查默认使用语音智能体类型，语言继承机器人且不在页面配置。
const emptySurvey = (): SatisfactionSurvey => ({ id: '', name: '', description: '', mode: 'voice_agent', metricType: 'custom', language: 'inherit', status: 'draft', version: 1, openingPrompt: '结束前，想邀请您评价本次服务。', closingPrompt: '感谢您的反馈，再见。', noInputPrompt: '', maxNoInputRetries: 1, responseCount: 0, updatedAt: Date.now(), reasonTraceEnabled: false, questions: [{ id: `question_${Date.now()}`, title: '您对本次服务是否满意？', prompt: '您对本次服务是否满意？', type: 'single_choice', required: true, options: [{ value: '1', label: '满意' }, { value: '2', label: '一般' }, { value: '3', label: '不满意' }] }] });

const SatisfactionSurveyManager: React.FC<Props> = ({ surveys, onChange, bots, onOpenCallRecord }) => {
  const [tab, setTab] = useState<'list' | 'report'>('list');
  const [editing, setEditing] = useState<SatisfactionSurvey | null>(null);
  const [keyword, setKeyword] = useState('');
  const [mode, setMode] = useState('all');
  const [status, setStatus] = useState('all');
  const [page, setPage] = useState(1);
  const filtered = useMemo(() => surveys.filter(item => (!keyword.trim() || `${item.name}${item.description}`.toLowerCase().includes(keyword.trim().toLowerCase())) && (mode === 'all' || item.mode === mode) && (status === 'all' || item.status === status)), [surveys, keyword, mode, status]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / 10));
  const rows = filtered.slice((Math.min(page, pageCount) - 1) * 10, Math.min(page, pageCount) * 10);
  const save = (item: SatisfactionSurvey) => { onChange(item.id ? surveys.map(old => old.id === item.id ? item : old) : [{ ...item, id: `survey_${Date.now()}` }, ...surveys]); setEditing(null); };
  const copy = (item: SatisfactionSurvey) => onChange([{ ...item, id: `survey_${Date.now()}`, name: `${item.name}（副本）`, status: 'draft', responseCount: 0, updatedAt: Date.now(), questions: item.questions.map((question, index) => ({ ...question, id: `question_${Date.now()}_${index}` })) }, ...surveys]);
  const remove = (item: SatisfactionSurvey) => { const used = bots.some(bot => bot.triggers?.some(trigger => trigger.actionConfig?.surveyId === item.id)); if (used) return window.alert('该调查已被机器人触发器使用，请先解除引用。'); if (item.responseCount) return window.alert('该调查已有回答，请停用后保留历史数据。'); if (window.confirm(`确定删除“${item.name}”吗？`)) onChange(surveys.filter(old => old.id !== item.id)); };
  if (editing) return <SatisfactionSurveyEditor survey={editing} onSave={save} onCancel={() => setEditing(null)} />;

  return <div className="mx-auto max-w-[1480px] p-6"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-bold text-slate-900">满意度调查</h2><p className="mt-1 text-sm text-slate-500">统一管理语音智能体和 IVR 调查，发布后由通话结束触发器引用。</p></div>{tab === 'list' && <button type="button" onClick={() => setEditing(emptySurvey())} className="flex items-center gap-1.5 rounded bg-primary px-4 py-2 text-sm font-semibold text-white"><Plus size={16} />新建调查</button>}</div>
    <div className="mb-4 flex border-b border-slate-200"><button type="button" onClick={() => setTab('list')} className={`flex items-center gap-1.5 border-b-2 px-4 py-3 text-sm font-semibold ${tab === 'list' ? 'border-primary text-primary' : 'border-transparent text-slate-500'}`}><FileText size={16} />问卷管理</button><button type="button" onClick={() => setTab('report')} className={`flex items-center gap-1.5 border-b-2 px-4 py-3 text-sm font-semibold ${tab === 'report' ? 'border-primary text-primary' : 'border-transparent text-slate-500'}`}><BarChart3 size={16} />满意度报表</button></div>
    {tab === 'report' ? <SatisfactionSurveyReport surveys={surveys} bots={bots} onOpenCallRecord={onOpenCallRecord} /> : <><div className="mb-4 flex gap-2 rounded-lg border border-slate-200 bg-white p-4"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={keyword} onChange={event => { setKeyword(event.target.value); setPage(1); }} placeholder="搜索调查名称或说明" className="w-full rounded border border-slate-200 py-2 pl-9 pr-3 text-sm" /></div><select value={mode} onChange={event => { setMode(event.target.value); setPage(1); }} className="rounded border border-slate-200 px-3 text-sm"><option value="all">全部采集方式</option><option value="voice_agent">语音智能体</option><option value="ivr">IVR</option></select><select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }} className="rounded border border-slate-200 px-3 text-sm"><option value="all">全部状态</option><option value="published">已发布</option><option value="draft">草稿</option><option value="disabled">已停用</option></select></div>
      <div className="overflow-hidden rounded-lg border border-slate-200 bg-white"><table className="w-full text-left"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">名称</th><th className="px-5 py-3">采集方式</th><th className="px-5 py-3">有效回答</th><th className="px-5 py-3">状态</th><th className="px-5 py-3">更新时间</th><th className="px-5 py-3 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(item => <tr key={item.id} className="text-sm"><td className="px-5 py-4"><button type="button" onClick={() => setEditing(item)} className="font-semibold text-slate-800 hover:text-primary">{item.name}</button><div className="mt-1 max-w-[360px] truncate text-xs text-slate-400">{item.description || '-'}</div></td><td className="px-5 py-4 text-slate-600">{item.mode === 'ivr' ? 'IVR' : '语音智能体'}</td><td className="px-5 py-4 text-slate-600">{item.responseCount.toLocaleString()}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-0.5 text-xs ${statusMeta[item.status][1]}`}>{statusMeta[item.status][0]}</span></td><td className="px-5 py-4 text-slate-500">{new Date(item.updatedAt).toLocaleString('zh-CN', { hour12: false })}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button type="button" onClick={() => setEditing(item)} className="p-1.5 text-slate-400 hover:text-primary" title="编辑"><Edit2 size={15} /></button><button type="button" onClick={() => copy(item)} className="p-1.5 text-slate-400 hover:text-primary" title="复制"><Copy size={15} /></button><button type="button" onClick={() => remove(item)} className="p-1.5 text-slate-400 hover:text-red-500" title="删除"><Trash2 size={15} /></button></div></td></tr>)}{!rows.length && <tr><td colSpan={6} className="px-5 py-16 text-center text-sm text-slate-400">没有符合条件的满意度调查</td></tr>}</tbody></table><div className="flex items-center justify-between border-t border-slate-100 px-5 py-3 text-xs text-slate-500"><span>共 {filtered.length} 条</span><div className="flex gap-2"><button type="button" disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="rounded border px-2 py-1 disabled:opacity-40">上一页</button><span>{Math.min(page, pageCount)} / {pageCount}</span><button type="button" disabled={page >= pageCount} onClick={() => setPage(value => value + 1)} className="rounded border px-2 py-1 disabled:opacity-40">下一页</button></div></div></div></>}
  </div>;
};

export default SatisfactionSurveyManager;
