import React from 'react';
import { Plus, Trash2, X } from 'lucide-react';
import {
  CONDITION_OPERATOR_LABELS,
  FOLLOW_UP_ACTION_LABELS,
  FOLLOW_UP_NODE_META,
  FollowUpActionType,
  FollowUpConditionRow,
  FollowUpFieldMappingRow,
  FollowUpGraphEdge,
  FollowUpGraphNode,
  FollowUpRuleGraphDefinition,
  FollowUpRuleVariable,
  getNodeOutputOptions,
} from './followUpRuleGraph';

interface Props {
  rule: FollowUpRuleGraphDefinition;
  node: FollowUpGraphNode | null;
  edge: FollowUpGraphEdge | null;
  onRuleChange: (rule: FollowUpRuleGraphDefinition) => void;
  onNodeChange: (node: FollowUpGraphNode) => void;
  onEdgeChange: (edge: FollowUpGraphEdge) => void;
  onDeleteNode: (nodeId: string) => void;
  onDeleteEdge: (edgeId: string) => void;
  onClose: () => void;
}

const inputClass = 'h-9 w-full rounded-md border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-primary';
const textAreaClass = 'w-full resize-none rounded-md border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700 outline-none focus:border-primary';
const createId = (prefix: string) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
const splitValues = (value: string) => value.split(',').map(item => item.trim()).filter(Boolean);
const BOT_OPTIONS = [['bot_didi_demo', '滴滴出行智能客服'], ['bot_agent_demo', '语音 Agent'], ['bot_review', '回访机器人']];
const FLOW_OPTIONS = [['main', '主入口 Flow'], ['lookup', '订单查询 Flow'], ['review', '满意度回访 Flow'], ['reminder', '预约提醒 Flow']];

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block"><span className="mb-1.5 block text-xs font-medium text-slate-600">{label}</span>{children}</label>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="border-b border-slate-100 px-5 py-5 last:border-b-0"><h4 className="mb-4 text-sm font-semibold text-slate-800">{title}</h4><div className="space-y-4">{children}</div></section>;
}

function SwitchRow({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <label className="flex items-center justify-between gap-3 text-sm text-slate-700"><span>{label}</span><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} className="h-4 w-4 accent-primary" /></label>;
}

function OptionChecklist({ options, values, onChange }: { options: string[][]; values: string[]; onChange: (values: string[]) => void }) {
  return <div className="grid grid-cols-1 gap-2 rounded-md border border-slate-200 p-3">{options.map(([value, label]) => <label key={value} className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" className="h-4 w-4 accent-primary" checked={values.includes(value)} onChange={event => onChange(event.target.checked ? [...values, value] : values.filter(item => item !== value))} />{label}</label>)}</div>;
}

function ConditionEditor({ rows, logic, onChange }: { rows: FollowUpConditionRow[]; logic: 'ALL' | 'ANY'; onChange: (rows: FollowUpConditionRow[], logic: 'ALL' | 'ANY') => void }) {
  return <div className="space-y-3">
    <div className="flex items-center justify-between"><span className="text-xs font-medium text-slate-600">条件关系</span><select className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs text-slate-700" value={logic} onChange={event => onChange(rows, event.target.value as 'ALL' | 'ANY')}><option value="ALL">全部满足</option><option value="ANY">任一满足</option></select></div>
    {rows.map((row, index) => <div key={row.id} className="rounded-md border border-slate-200 p-3">
      <div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium text-slate-500">条件 {index + 1}</span><button type="button" className="text-slate-400 hover:text-rose-600" onClick={() => onChange(rows.filter(item => item.id !== row.id), logic)} aria-label="删除条件"><Trash2 size={14} /></button></div>
      <div className="grid grid-cols-[1fr_104px] gap-2"><input className={inputClass} value={row.field} placeholder="字段" onChange={event => onChange(rows.map(item => item.id === row.id ? { ...item, field: event.target.value } : item), logic)} /><select className={inputClass} value={row.operator} onChange={event => onChange(rows.map(item => item.id === row.id ? { ...item, operator: event.target.value as FollowUpConditionRow['operator'] } : item), logic)}>{Object.entries(CONDITION_OPERATOR_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
      {!['exists', 'not_exists'].includes(row.operator) && <input className={`${inputClass} mt-2`} value={row.value || ''} placeholder="比较值" onChange={event => onChange(rows.map(item => item.id === row.id ? { ...item, value: event.target.value } : item), logic)} />}
    </div>)}
    <button type="button" className="flex h-9 w-full items-center justify-center gap-1 rounded-md border border-dashed border-slate-300 text-xs font-medium text-slate-600 hover:border-primary hover:text-primary" onClick={() => onChange([...rows, { id: createId('condition'), field: '', operator: 'equals', valueType: 'text', value: '' }], logic)}><Plus size={14} />添加条件</button>
  </div>;
}

function MappingEditor({ rows, onChange, sourceLabel = '来源字段', targetLabel = '目标变量' }: { rows: FollowUpFieldMappingRow[]; onChange: (rows: FollowUpFieldMappingRow[]) => void; sourceLabel?: string; targetLabel?: string }) {
  return <div className="space-y-2">
    {rows.map(row => <div key={row.id} className="grid grid-cols-[1fr_1fr_28px] gap-2"><input className={inputClass} value={row.sourceKey} placeholder={sourceLabel} onChange={event => onChange(rows.map(item => item.id === row.id ? { ...item, sourceKey: event.target.value } : item))} /><input className={inputClass} value={row.targetKey} placeholder={targetLabel} onChange={event => onChange(rows.map(item => item.id === row.id ? { ...item, targetKey: event.target.value } : item))} /><button type="button" className="flex items-center justify-center text-slate-400 hover:text-rose-600" onClick={() => onChange(rows.filter(item => item.id !== row.id))} aria-label="删除映射"><Trash2 size={14} /></button></div>)}
    <button type="button" className="flex h-9 w-full items-center justify-center gap-1 rounded-md border border-dashed border-slate-300 text-xs font-medium text-slate-600 hover:border-primary hover:text-primary" onClick={() => onChange([...rows, { id: createId('mapping'), sourceKey: '', targetKey: '', valueType: 'text' }])}><Plus size={14} />添加映射</button>
  </div>;
}

function VariableEditor({ variables, onChange }: { variables: FollowUpRuleVariable[]; onChange: (variables: FollowUpRuleVariable[]) => void }) {
  return <div className="space-y-2">
    {variables.map(variable => <div key={variable.key} className="rounded-md border border-slate-200 p-3"><div className="grid grid-cols-[1fr_1fr_30px] gap-2"><input className={inputClass} value={variable.label} placeholder="名称" onChange={event => onChange(variables.map(item => item.key === variable.key ? { ...item, label: event.target.value } : item))} /><input className={inputClass} value={variable.key} placeholder="变量名" onChange={event => onChange(variables.map(item => item.key === variable.key ? { ...item, key: event.target.value } : item))} /><button type="button" className="flex items-center justify-center text-slate-400 hover:text-rose-600" onClick={() => onChange(variables.filter(item => item.key !== variable.key))} aria-label="删除变量"><Trash2 size={14} /></button></div><div className="mt-2 grid grid-cols-2 gap-2"><select className={inputClass} value={variable.type} onChange={event => onChange(variables.map(item => item.key === variable.key ? { ...item, type: event.target.value as FollowUpRuleVariable['type'] } : item))}><option value="string">文本</option><option value="number">数字</option><option value="boolean">布尔值</option><option value="datetime">日期时间</option></select><input className={inputClass} value={variable.defaultValue || ''} placeholder="默认值" onChange={event => onChange(variables.map(item => item.key === variable.key ? { ...item, defaultValue: event.target.value } : item))} /></div></div>)}
    <button type="button" className="flex h-9 w-full items-center justify-center gap-1 rounded-md border border-dashed border-slate-300 text-xs font-medium text-slate-600 hover:border-primary hover:text-primary" onClick={() => onChange([...variables, { key: createId('variable'), label: '新变量', type: 'string', sourceType: 'fixed' }])}><Plus size={14} />添加变量</button>
  </div>;
}

function RuleInspector({ rule, onChange }: { rule: FollowUpRuleGraphDefinition; onChange: (rule: FollowUpRuleGraphDefinition) => void }) {
  return <>
    <Section title="基本信息"><Field label="规则名称"><input className={inputClass} value={rule.name} onChange={event => onChange({ ...rule, name: event.target.value })} /></Field><Field label="规则说明"><textarea rows={3} className={textAreaClass} value={rule.description} onChange={event => onChange({ ...rule, description: event.target.value })} /></Field><div className="grid grid-cols-3 gap-3"><Field label="规则优先级"><input type="number" min={1} max={999} className={inputClass} value={rule.priority ?? 100} onChange={event => onChange({ ...rule, priority: Number(event.target.value) || 1 })} /></Field><Field label="有效期（天）"><input type="number" min={1} className={inputClass} value={rule.validityDays} onChange={event => onChange({ ...rule, validityDays: Number(event.target.value) || 1 })} /></Field><Field label="冲突处理"><select className={inputClass} value={rule.conflictStrategy} onChange={event => onChange({ ...rule, conflictStrategy: event.target.value as FollowUpRuleGraphDefinition['conflictStrategy'] })}><option value="latest">保留最新任务</option><option value="highest_priority">按规则优先级</option><option value="manual">转人工处理</option></select></Field></div></Section>
    <Section title="适用范围"><Field label="机器人"><OptionChecklist options={BOT_OPTIONS} values={rule.scope.botIds} onChange={botIds => onChange({ ...rule, scope: { ...rule.scope, botIds } })} /></Field><Field label="Flow"><OptionChecklist options={FLOW_OPTIONS} values={rule.scope.flowIds} onChange={flowIds => onChange({ ...rule, scope: { ...rule.scope, flowIds } })} /></Field></Section>
    <Section title="任务去重"><Field label="去重字段"><input className={inputClass} value={rule.dedupeFieldKeys.join(', ')} onChange={event => onChange({ ...rule, dedupeFieldKeys: splitValues(event.target.value) })} /></Field><Field label="重复任务处理"><select className={inputClass} value={rule.dedupeStrategy} onChange={event => onChange({ ...rule, dedupeStrategy: event.target.value as FollowUpRuleGraphDefinition['dedupeStrategy'] })}><option value="ignore">忽略新任务</option><option value="update">更新原任务</option><option value="merge">合并任务数据</option></select></Field></Section>
    <Section title="流程变量"><VariableEditor variables={rule.variables} onChange={variables => onChange({ ...rule, variables })} /></Section>
  </>;
}

function TriggerConfig({ node, change }: { node: FollowUpGraphNode; change: (config: FollowUpGraphNode['config']) => void }) {
  const config = node.config;
  const events = config.triggerSourceType === 'task' ? [['no_answer', '未接通'], ['task_completed', '任务完成'], ['task_failed', '任务失败']] : config.triggerSourceType === 'external' ? [['order_changed', '订单状态变化'], ['appointment_changed', '预约状态变化'], ['complaint_created', '投诉创建'], ['custom_event', '自定义事件']] : [['later_contact', '用户要求稍后联系'], ['specified_time', '用户指定联系时间'], ['call_ended', '通话结束'], ['negative_feedback', '负面反馈']];
  return <><Section title="触发事件"><Field label="事件来源"><select className={inputClass} value={config.triggerSourceType || 'call'} onChange={event => change({ ...config, triggerSourceType: event.target.value as typeof config.triggerSourceType, triggerEventType: '' })}><option value="call">通话事件</option><option value="task">跟进任务</option><option value="external">业务系统</option></select></Field><Field label="事件类型"><select className={inputClass} value={config.triggerEventType || ''} onChange={event => change({ ...config, triggerEventType: event.target.value, triggerEvent: event.target.value })}><option value="">请选择</option>{events.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></Section><Section title="触发条件"><ConditionEditor rows={config.triggerConditions || []} logic={config.triggerConditionsLogic || 'ALL'} onChange={(triggerConditions, triggerConditionsLogic) => change({ ...config, triggerConditions, triggerConditionsLogic })} /></Section><Section title="重复触发"><Field label="去重字段"><input className={inputClass} value={(config.triggerDedupeFieldKeys || []).join(', ')} onChange={event => change({ ...config, triggerDedupeFieldKeys: splitValues(event.target.value) })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="去重时间（分钟）"><input type="number" min={0} className={inputClass} value={config.dedupeWindowMinutes ?? 30} onChange={event => change({ ...config, dedupeWindowMinutes: Number(event.target.value) })} /></Field><Field label="重复处理"><select className={inputClass} value={config.triggerRepeatStrategy || 'ignore'} onChange={event => change({ ...config, triggerRepeatStrategy: event.target.value as typeof config.triggerRepeatStrategy })}><option value="ignore">忽略</option><option value="update">更新原任务</option><option value="merge">合并数据</option></select></Field></div></Section><Section title="初始变量映射"><MappingEditor rows={config.triggerMappings || []} onChange={triggerMappings => change({ ...config, triggerMappings })} /></Section></>;
}

function WaitConfig({ node, rule, change }: { node: FollowUpGraphNode; rule: FollowUpRuleGraphDefinition; change: (config: FollowUpGraphNode['config']) => void }) {
  const config = node.config;
  return <><Section title="等待时间"><Field label="时间来源"><select className={inputClass} value={config.waitBaseTime || 'now'} onChange={event => change({ ...config, waitBaseTime: event.target.value as typeof config.waitBaseTime })}><option value="now">当前时间</option><option value="variable">流程变量</option></select></Field>{config.waitBaseTime === 'variable' && <Field label="时间变量"><select className={inputClass} value={config.waitVariableKey || ''} onChange={event => change({ ...config, waitVariableKey: event.target.value, dateVariable: event.target.value })}><option value="">请选择</option>{rule.variables.filter(item => item.type === 'datetime').map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select></Field>}<div className="grid grid-cols-[96px_1fr_100px] gap-2"><select className={inputClass} value={config.waitOffsetDirection || 'after'} onChange={event => change({ ...config, waitOffsetDirection: event.target.value as typeof config.waitOffsetDirection })}><option value="before">提前</option><option value="after">延后</option></select><input type="number" min={0} className={inputClass} value={config.waitOffsetAmount ?? 1} onChange={event => change({ ...config, waitOffsetAmount: Number(event.target.value), waitAmount: Number(event.target.value) })} /><select className={inputClass} value={config.waitOffsetUnit || 'hour'} onChange={event => change({ ...config, waitOffsetUnit: event.target.value as typeof config.waitOffsetUnit, waitUnit: event.target.value as typeof config.waitUnit })}><option value="minute">分钟</option><option value="hour">小时</option><option value="day">天</option></select></div></Section><Section title="执行窗口"><SwitchRow label="限制执行时段" checked={Boolean(config.waitWindowEnabled)} onChange={waitWindowEnabled => change({ ...config, waitWindowEnabled })} />{config.waitWindowEnabled && <div className="grid grid-cols-2 gap-3"><Field label="开始时间"><input type="time" className={inputClass} value={config.waitWindowStart || '09:00'} onChange={event => change({ ...config, waitWindowStart: event.target.value })} /></Field><Field label="结束时间"><input type="time" className={inputClass} value={config.waitWindowEnd || '20:00'} onChange={event => change({ ...config, waitWindowEnd: event.target.value })} /></Field></div>}<Field label="时间无效时"><select className={inputClass} value={config.waitInvalidStrategy || 'use_default'} onChange={event => change({ ...config, waitInvalidStrategy: event.target.value as typeof config.waitInvalidStrategy })}><option value="use_default">使用默认时间</option><option value="skip">跳过等待</option><option value="manual">转人工</option><option value="fail">结束任务</option></select></Field></Section></>;
}

function ProtectionConfig({ node, change }: { node: FollowUpGraphNode; change: (config: FollowUpGraphNode['config']) => void }) {
  const config = node.config;
  return <><Section title="保护策略"><Field label="策略模板"><select className={inputClass} value={config.protectionTemplateId || 'default'} onChange={event => change({ ...config, protectionTemplateId: event.target.value })}><option value="default">平台默认策略</option><option value="service">服务通知策略</option><option value="marketing">营销触达策略</option><option value="custom">自定义策略</option></select></Field><Field label="频控对象"><select className={inputClass} value={config.protectionTarget || 'phone'} onChange={event => change({ ...config, protectionTarget: event.target.value as typeof config.protectionTarget })}><option value="phone">手机号</option><option value="customer">客户</option><option value="order">订单</option></select></Field><div className="grid grid-cols-2 gap-3"><Field label="每日最多"><input type="number" min={0} className={inputClass} value={config.maxDailyCalls ?? 1} onChange={event => change({ ...config, maxDailyCalls: Number(event.target.value) })} /></Field><Field label="每周最多"><input type="number" min={0} className={inputClass} value={config.maxWeeklyCalls ?? 3} onChange={event => change({ ...config, maxWeeklyCalls: Number(event.target.value) })} /></Field></div><div className="grid grid-cols-2 gap-3"><Field label="最短间隔（分钟）"><input type="number" min={0} className={inputClass} value={config.minIntervalMinutes ?? 60} onChange={event => change({ ...config, minIntervalMinutes: Number(event.target.value) })} /></Field><Field label="拒绝冷却（天）"><input type="number" min={0} className={inputClass} value={config.rejectCooldownDays ?? 14} onChange={event => change({ ...config, rejectCooldownDays: Number(event.target.value) })} /></Field></div></Section><Section title="拦截条件"><SwitchRow label="夜间不触达" checked={Boolean(config.avoidNightCalls)} onChange={avoidNightCalls => change({ ...config, avoidNightCalls })} /><SwitchRow label="节假日不触达" checked={Boolean(config.avoidHolidays)} onChange={avoidHolidays => change({ ...config, avoidHolidays })} /><SwitchRow label="投诉风险客户" checked={Boolean(config.blockComplaintRisk)} onChange={blockComplaintRisk => change({ ...config, blockComplaintRisk })} /><SwitchRow label="黑名单客户" checked={Boolean(config.blockBlacklist)} onChange={blockBlacklist => change({ ...config, blockBlacklist })} /><SwitchRow label="人工处理中" checked={Boolean(config.blockInService)} onChange={blockInService => change({ ...config, blockInService })} /></Section></>;
}

function ActionConfig({ node, rule, change }: { node: FollowUpGraphNode; rule: FollowUpRuleGraphDefinition; change: (config: FollowUpGraphNode['config']) => void }) {
  const config = node.config;
  const type = config.actionType || 'auto_call';
  return <><Section title="动作类型"><Field label="执行动作"><select className={inputClass} value={type} onChange={event => change({ ...config, actionType: event.target.value as FollowUpActionType })}>{Object.entries(FOLLOW_UP_ACTION_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></Section>
    {type === 'auto_call' && <Section title="自动外呼"><Field label="执行机器人"><select className={inputClass} value={config.executionBotId || config.executionBotIds?.[0] || ''} onChange={event => change({ ...config, executionBotId: event.target.value, executionBotIds: event.target.value ? [event.target.value] : [] })}><option value="">请选择</option>{BOT_OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="接通后进入 Flow"><select className={inputClass} value={config.executionFlowId || config.executionFlowIds?.[0] || ''} onChange={event => change({ ...config, executionFlowId: event.target.value, executionFlowIds: event.target.value ? [event.target.value] : [] })}><option value="">请选择</option>{FLOW_OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="被叫号码变量"><select className={inputClass} value={config.parameterMappings?.[0]?.sourceKey || 'customer.phone'} onChange={event => change({ ...config, parameterMappings: [{ id: config.parameterMappings?.[0]?.id || createId('phone'), sourceKey: event.target.value, targetKey: 'phone', valueType: 'variable', required: true }] })}>{rule.variables.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select></Field></Section>}
    {type === 'send_sms' && <Section title="短信"><Field label="短信模板"><select className={inputClass} value={config.smsTemplateId || ''} onChange={event => change({ ...config, smsTemplateId: event.target.value })}><option value="">请选择</option><option value="appointment_reminder">预约提醒</option><option value="follow_up_notice">跟进通知</option><option value="service_review">服务回访</option></select></Field><Field label="接收号码变量"><select className={inputClass} value={config.parameterMappings?.[0]?.sourceKey || ''} onChange={event => change({ ...config, parameterMappings: [{ id: config.parameterMappings?.[0]?.id || createId('phone'), sourceKey: event.target.value, targetKey: 'phone', valueType: 'variable', required: true }] })}><option value="">请选择</option>{rule.variables.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select></Field></Section>}
    {type === 'manual_task' && <Section title="人工任务"><Field label="处理队列"><select className={inputClass} value={config.manualQueueId || ''} onChange={event => change({ ...config, manualQueueId: event.target.value })}><option value="">请选择</option><option value="customer_success">客户服务</option><option value="quality_review">质量回访</option><option value="complaint">投诉处理</option></select></Field></Section>}
    {type === 'call_tool' && <Section title="调用工具"><Field label="工具"><select className={inputClass} value={config.toolId || ''} onChange={event => change({ ...config, toolId: event.target.value })}><option value="">请选择</option><option value="query_order">查询订单</option><option value="create_ticket">创建工单</option><option value="update_customer">更新客户</option></select></Field><Field label="参数映射"><MappingEditor rows={config.parameterMappings || []} onChange={parameterMappings => change({ ...config, parameterMappings })} /></Field><Field label="结果映射"><MappingEditor rows={config.resultMappings || []} sourceLabel="返回字段" targetLabel="流程变量" onChange={resultMappings => change({ ...config, resultMappings })} /></Field></Section>}
    {type === 'write_back' && <Section title="回写数据"><Field label="回写对象"><select className={inputClass} value={config.writeBackTarget || ''} onChange={event => change({ ...config, writeBackTarget: event.target.value })}><option value="">请选择</option><option value="customer">客户</option><option value="order">订单</option><option value="ticket">工单</option><option value="task">跟进任务</option></select></Field><Field label="字段映射"><MappingEditor rows={config.writeBackRows || []} sourceLabel="值来源" targetLabel="目标字段" onChange={writeBackRows => change({ ...config, writeBackRows })} /></Field></Section>}
    <Section title="执行控制"><div className="grid grid-cols-3 gap-2"><Field label="超时（秒）"><input type="number" min={1} className={inputClass} value={config.timeoutSeconds ?? 30} onChange={event => change({ ...config, timeoutSeconds: Number(event.target.value) })} /></Field><Field label="技术重试"><input type="number" min={0} className={inputClass} value={config.retryCount ?? 0} onChange={event => change({ ...config, retryCount: Number(event.target.value) })} /></Field><Field label="间隔（分钟）"><input type="number" min={0} className={inputClass} value={config.retryIntervalMinutes ?? 1} onChange={event => change({ ...config, retryIntervalMinutes: Number(event.target.value) })} /></Field></div><Field label="幂等键"><input className={inputClass} value={config.idempotencyKey || ''} onChange={event => change({ ...config, idempotencyKey: event.target.value })} /></Field></Section>
  </>;
}

function EndConfig({ node, rule, change }: { node: FollowUpGraphNode; rule: FollowUpRuleGraphDefinition; change: (config: FollowUpGraphNode['config']) => void }) {
  const config = node.config;
  const resultSource = config.resultCodeSource || 'dictionary';
  return <><Section title="任务结果"><Field label="任务状态"><select className={inputClass} value={config.resultStatus || 'completed'} onChange={event => change({ ...config, resultStatus: event.target.value })}><option value="completed">已完成</option><option value="rejected">客户拒绝</option><option value="cancelled">已取消</option><option value="expired">已过期</option><option value="transferred">已转人工</option><option value="failed">失败</option></select></Field><Field label="结果来源"><select className={inputClass} value={resultSource} onChange={event => change({ ...config, resultCodeSource: event.target.value as typeof config.resultCodeSource, resultCode: '' })}><option value="dictionary">平台结果字典</option><option value="flow">Flow 输出</option><option value="tool">工具返回</option></select></Field><Field label="业务结果编码">{resultSource === 'dictionary' ? <select className={inputClass} value={config.resultCode || ''} onChange={event => change({ ...config, resultCode: event.target.value })}><option value="">请选择</option><option value="FOLLOW_UP_COMPLETED">跟进完成</option><option value="REVIEW_COMPLETED">回访完成</option><option value="CUSTOMER_REJECTED">客户拒绝</option><option value="SATISFACTION_EXISTS">已有满意度</option><option value="NO_ANSWER_MAX_RETRY">未接通达到上限</option><option value="MANUAL_FOLLOW_UP">人工跟进</option><option value="MANUAL_REVIEW">人工回访</option><option value="TOUCH_BLOCKED">触达受限</option><option value="TASK_EXPIRED">任务过期</option></select> : <select className={inputClass} value={config.resultCode || ''} onChange={event => change({ ...config, resultCode: event.target.value })}><option value="">请选择结果变量</option>{rule.variables.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select>}</Field><Field label="报表分类"><select className={inputClass} value={config.reportCategory || 'success'} onChange={event => change({ ...config, reportCategory: event.target.value as typeof config.reportCategory })}><option value="success">成功</option><option value="failure">失败</option><option value="manual">人工接管</option><option value="blocked">保护拦截</option><option value="expired">过期</option></select></Field></Section><Section title="结果回写"><Field label="客户标签"><input className={inputClass} value={config.writeBackTags || ''} onChange={event => change({ ...config, writeBackTags: event.target.value })} /></Field><SwitchRow label="发送业务事件" checked={Boolean(config.emitEvent)} onChange={emitEvent => change({ ...config, emitEvent })} /></Section></>;
}

function NodeInspector({ rule, node, onChange, onDelete }: { rule: FollowUpRuleGraphDefinition; node: FollowUpGraphNode; onChange: (node: FollowUpGraphNode) => void; onDelete: () => void }) {
  const changeConfig = (config: FollowUpGraphNode['config']) => onChange({ ...node, config });
  return <><Section title="节点信息"><Field label="节点名称"><input className={inputClass} value={node.title} onChange={event => onChange({ ...node, title: event.target.value })} /></Field><Field label="节点说明"><textarea rows={2} className={textAreaClass} value={node.description} onChange={event => onChange({ ...node, description: event.target.value })} /></Field></Section>{node.type === 'trigger' && <TriggerConfig node={node} change={changeConfig} />}{node.type === 'condition' && <Section title="判断条件"><ConditionEditor rows={node.config.conditionRows || []} logic={node.config.conditionLogic || 'ALL'} onChange={(conditionRows, conditionLogic) => changeConfig({ ...node.config, conditionRows, conditionLogic })} /></Section>}{node.type === 'wait' && <WaitConfig node={node} rule={rule} change={changeConfig} />}{node.type === 'protection' && <ProtectionConfig node={node} change={changeConfig} />}{node.type === 'action' && <ActionConfig node={node} rule={rule} change={changeConfig} />}{node.type === 'end' && <EndConfig node={node} rule={rule} change={changeConfig} />}<div className="p-5"><button type="button" onClick={onDelete} className="flex h-9 w-full items-center justify-center gap-2 rounded-md border border-rose-200 text-sm font-medium text-rose-600 hover:bg-rose-50"><Trash2 size={15} />删除节点</button></div></>;
}

function EdgeInspector({ rule, edge, onChange, onDelete }: { rule: FollowUpRuleGraphDefinition; edge: FollowUpGraphEdge; onChange: (edge: FollowUpGraphEdge) => void; onDelete: () => void }) {
  const source = rule.nodes.find(item => item.id === edge.source);
  const options = source ? getNodeOutputOptions(source) : [];
  const displayedOptions = options.some(item => item.value === 'default') ? options : [...options, { value: 'default', label: '默认分支' }];
  return <><Section title="流转配置"><Field label="来源节点"><select className={inputClass} value={edge.source} onChange={event => { const nextSource = rule.nodes.find(item => item.id === event.target.value); const first = nextSource ? getNodeOutputOptions(nextSource)[0]?.value || 'default' : 'default'; onChange({ ...edge, source: event.target.value, sourceHandle: first, isDefault: false }); }}>{rule.nodes.filter(item => item.type !== 'end').map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="来源结果"><select className={inputClass} value={edge.sourceHandle} onChange={event => onChange({ ...edge, sourceHandle: event.target.value, isDefault: event.target.value === 'default' })}>{displayedOptions.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field><Field label="目标节点"><select className={inputClass} value={edge.target} onChange={event => onChange({ ...edge, target: event.target.value })}>{rule.nodes.filter(item => item.id !== edge.source && item.type !== 'trigger').map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="分支名称"><input className={inputClass} value={edge.label} onChange={event => onChange({ ...edge, label: event.target.value })} /></Field><SwitchRow label="默认分支" checked={Boolean(edge.isDefault)} onChange={isDefault => onChange({ ...edge, isDefault, sourceHandle: isDefault ? 'default' : options[0]?.value || 'default' })} /></Section><div className="p-5"><button type="button" onClick={onDelete} className="flex h-9 w-full items-center justify-center gap-2 rounded-md border border-rose-200 text-sm font-medium text-rose-600 hover:bg-rose-50"><Trash2 size={15} />删除连线</button></div></>;
}

export default function FollowUpRuleInspector({ rule, node, edge, onRuleChange, onNodeChange, onEdgeChange, onDeleteNode, onDeleteEdge, onClose }: Props) {
  const title = node ? FOLLOW_UP_NODE_META[node.type].label : edge ? '分支配置' : '规则设置';
  return <aside className="absolute bottom-4 right-4 top-[78px] z-40 flex w-[390px] flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-xl"><header className="flex h-14 shrink-0 items-center justify-between border-b border-slate-200 px-5"><div><h3 className="text-sm font-semibold text-slate-900">{title}</h3>{node && <div className="mt-0.5 text-[11px] text-slate-400">{node.title}</div>}</div><button type="button" onClick={onClose} className="rounded-md p-2 text-slate-400 hover:bg-slate-100" aria-label="关闭配置"><X size={17} /></button></header><div className="min-h-0 flex-1 overflow-y-auto">{node ? <NodeInspector rule={rule} node={node} onChange={onNodeChange} onDelete={() => onDeleteNode(node.id)} /> : edge ? <EdgeInspector rule={rule} edge={edge} onChange={onEdgeChange} onDelete={() => onDeleteEdge(edge.id)} /> : <RuleInspector rule={rule} onChange={onRuleChange} />}</div></aside>;
}
