/** 将多个接口编排为可复用、可对外开放的调用服务。 */
import React, { useMemo, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, Braces, CheckCircle2, Plus, Save, Search, Trash2 } from 'lucide-react';
import { ExtractionConfig, ExtractionWorkflow, ExtractionWorkflowStep, WorkflowContractField, WorkflowInputMapping, WorkflowOutputMapping } from '../../types';

interface Props { workflows: ExtractionWorkflow[]; onUpdate: (items: ExtractionWorkflow[]) => void; interfaces: ExtractionConfig[]; }

const createStep = (interfaces: ExtractionConfig[], index: number): ExtractionWorkflowStep => ({ id: `step_${Date.now()}_${index}`, name: `步骤 ${index + 1}`, interfaceId: interfaces[0]?.id ?? '', inputMappings: [], outputMappings: [], failureAction: 'stop', retryCount: 0, timeoutSeconds: 10 });
const createWorkflow = (interfaces: ExtractionConfig[]): ExtractionWorkflow => ({ id: `workflow_${Date.now()}`, name: '', description: '', serviceKey: '', status: 'draft', lastUpdated: Date.now(), inputs: [], outputs: [], steps: [createStep(interfaces, 0)] });

/** 检查工作流是否具备可执行、可发布的完整配置。 */
function validateWorkflow(workflow: ExtractionWorkflow): string[] {
  const issues: string[] = [];
  if (!workflow.name.trim()) issues.push('请填写工作流名称');
  if (!/^[a-z][a-z0-9_]*$/.test(workflow.serviceKey)) issues.push('服务标识只能使用小写字母、数字和下划线，并以字母开头');
  if (!workflow.inputs.length) issues.push('请至少定义一个服务输入');
  if (!workflow.outputs.length) issues.push('请至少定义一个服务输出');
  const inputKeys = workflow.inputs.map((item) => item.key.trim());
  const outputKeys = workflow.outputs.map((item) => item.key.trim());
  if (inputKeys.some((key) => !key) || new Set(inputKeys).size !== inputKeys.length) issues.push('服务输入字段不能为空或重复');
  if (outputKeys.some((key) => !key) || new Set(outputKeys).size !== outputKeys.length) issues.push('服务输出字段不能为空或重复');
  workflow.outputs.forEach((output) => { if (!output.sourceStepId || !output.sourceValue) issues.push(`服务输出“${output.key || '未命名'}”尚未绑定步骤输出`); });
  workflow.steps.forEach((step, index) => {
    if (!step.interfaceId) issues.push(`步骤 ${index + 1} 尚未选择接口`);
    step.inputMappings.forEach((mapping) => {
      if (!mapping.targetKey || !mapping.sourceValue) issues.push(`步骤 ${index + 1} 存在未完成的输入映射`);
      if (mapping.source === 'step_output') {
        const sourceIndex = workflow.steps.findIndex((item) => item.id === mapping.sourceStepId);
        if (sourceIndex < 0 || sourceIndex >= index) issues.push(`步骤 ${index + 1} 只能引用前序步骤输出`);
      }
    });
    step.outputMappings.forEach((mapping) => { if (!mapping.outputKey || !mapping.sourcePath) issues.push(`步骤 ${index + 1} 存在未完成的输出映射`); });
    if (step.failureAction === 'skip') {
      const isReferenced = workflow.steps.slice(index + 1).some((laterStep) => laterStep.inputMappings.some((mapping) => mapping.sourceStepId === step.id)) || workflow.outputs.some((output) => output.sourceStepId === step.id);
      if (isReferenced) issues.push(`步骤 ${index + 1} 的输出被后续使用，失败时不能选择“跳过并继续”`);
    }
  });
  return [...new Set(issues)];
}

export default function ExtractionWorkflowManager({ workflows, onUpdate, interfaces }: Props) {
  const [editing, setEditing] = useState<ExtractionWorkflow | null>(null);
  const [selectedStepId, setSelectedStepId] = useState('');
  const [showValidation, setShowValidation] = useState(false);
  const issues = useMemo(() => editing ? validateWorkflow(editing) : [], [editing]);
  const save = () => {
    if (!editing?.name.trim() || !editing.serviceKey.trim()) return;
    const next = { ...editing, lastUpdated: Date.now() };
    onUpdate(workflows.some((item) => item.id === next.id) ? workflows.map((item) => item.id === next.id ? next : item) : [next, ...workflows]);
    setEditing(null);
  };
  const copy = (source: ExtractionWorkflow) => onUpdate([{ ...source, id: `workflow_${Date.now()}`, name: `${source.name} - 副本`, serviceKey: `${source.serviceKey}_copy`, status: 'draft', lastUpdated: Date.now() }, ...workflows]);
  const remove = (id: string) => { if (window.confirm('确认删除这个接口工作流吗？')) onUpdate(workflows.filter((item) => item.id !== id)); };
  const create = () => { const next = createWorkflow(interfaces); setEditing(next); setSelectedStepId(next.steps[0]?.id ?? ''); };
  const edit = (item: ExtractionWorkflow) => { setEditing(item); setSelectedStepId(item.steps[0]?.id ?? ''); };

  if (!editing) return <WorkflowList items={workflows} interfaces={interfaces} onCreate={create} onEdit={edit} onCopy={copy} onDelete={remove} />;
  const selected = editing.steps.find((step) => step.id === selectedStepId) ?? editing.steps[0];
  const updateStep = (next: ExtractionWorkflowStep) => setEditing({ ...editing, steps: editing.steps.map((step) => step.id === next.id ? next : step) });
  return <div className="p-8 max-w-7xl mx-auto w-full pb-20">
    <div className="flex items-start justify-between mb-6"><div><button onClick={() => setEditing(null)} className="mb-3 flex items-center text-sm text-slate-400 hover:text-primary"><ArrowLeft size={16} className="mr-1" />返回工作流列表</button><h1 className="text-2xl font-bold text-slate-900">{editing.name ? '编辑接口工作流' : '新建接口工作流'}</h1><p className="mt-1 text-sm text-slate-500">定义服务入参与出参，按顺序调用接口，发布后可作为一个整体服务使用。</p></div><div className="flex gap-3"><button onClick={() => setShowValidation(true)} className="button-secondary"><CheckCircle2 size={16} />校验工作流</button><button disabled={!editing.name.trim() || !editing.serviceKey.trim()} onClick={save} className="button-primary"><Save size={16} />保存</button></div></div>
    {showValidation && <div className={`mb-5 rounded-lg border px-4 py-3 text-sm ${issues.length ? 'border-amber-200 bg-amber-50 text-amber-800' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{issues.length ? <><div className="font-semibold">发现 {issues.length} 个配置问题</div><ul className="mt-2 list-disc space-y-1 pl-5">{issues.map((issue) => <li key={issue}>{issue}</li>)}</ul></> : '校验通过，可以发布和调用。'}</div>}
    <ServiceContract workflow={editing} onChange={(next) => { setEditing(next); setShowValidation(false); }} />
    <section className="mt-5 rounded-xl border border-slate-200 bg-white overflow-hidden"><div className="border-b px-6 py-5"><h2 className="font-bold text-slate-800">执行步骤</h2><p className="mt-1 text-xs text-slate-500">步骤按顺序执行；输入只来自服务入参、前序步骤输出或固定值，确保不同调用方获得一致结果。</p></div><div className="grid grid-cols-1 xl:grid-cols-[360px_1fr] min-h-[520px]">
      <div className="border-r bg-slate-50 p-5">{editing.steps.map((step, index) => <React.Fragment key={step.id}><button onClick={() => setSelectedStepId(step.id)} className={`w-full rounded-lg border bg-white p-4 text-left ${selected?.id === step.id ? 'border-primary ring-2 ring-sky-100' : 'border-slate-200'}`}><div className="flex items-start justify-between"><div><div className="text-xs text-primary font-semibold">步骤 {index + 1}</div><div className="mt-1 font-semibold text-slate-800">{step.name}</div><div className="mt-1 text-xs text-slate-400">{interfaces.find((item) => item.id === step.interfaceId)?.name || '未选择接口'}</div></div><span className="text-xs text-slate-400">{step.inputMappings.length} 入 / {step.outputMappings.length} 出</span></div></button>{index < editing.steps.length - 1 && <div className="flex justify-center py-2"><ArrowDown size={16} className="text-slate-300" /></div>}</React.Fragment>)}<button onClick={() => { const step = createStep(interfaces, editing.steps.length); setEditing({ ...editing, steps: [...editing.steps, step] }); setSelectedStepId(step.id); }} className="mt-4 w-full rounded-lg border border-dashed border-slate-300 py-3 text-sm text-slate-500 hover:border-primary hover:text-primary"><Plus size={15} className="inline mr-1" />添加接口步骤</button></div>
      <div className="p-6">{selected && <StepEditor step={selected} stepIndex={editing.steps.findIndex((item) => item.id === selected.id)} allSteps={editing.steps} interfaces={interfaces} onChange={updateStep} onMove={(direction) => { const index = editing.steps.findIndex((item) => item.id === selected.id); const target = index + direction; if (target < 0 || target >= editing.steps.length) return; const steps = [...editing.steps]; [steps[index], steps[target]] = [steps[target], steps[index]]; setEditing({ ...editing, steps }); }} onDelete={() => { const steps = editing.steps.filter((item) => item.id !== selected.id); setEditing({ ...editing, steps }); setSelectedStepId(steps[0]?.id ?? ''); }} />}</div>
    </div></section>
  </div>;
}

/** 工作流列表提供查询、分页和对外开放状态。 */
function WorkflowList({ items, interfaces, onCreate, onEdit, onCopy, onDelete }: { items: ExtractionWorkflow[]; interfaces: ExtractionConfig[]; onCreate: () => void; onEdit: (item: ExtractionWorkflow) => void; onCopy: (item: ExtractionWorkflow) => void; onDelete: (id: string) => void }) {
  const [keyword, setKeyword] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 10;
  const filtered = items.filter((item) => `${item.name} ${item.description} ${item.serviceKey}`.toLowerCase().includes(keyword.trim().toLowerCase()));
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const currentPage = Math.min(page, pageCount);
  const visible = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  return <div className="p-8 max-w-7xl mx-auto w-full"><div className="flex items-start justify-between mb-6"><div><h1 className="text-2xl font-bold text-slate-900">接口工作流</h1><p className="text-sm text-slate-500 mt-1">单个接口组成工作流，工作流发布后成为一个新的调用服务。</p></div><button disabled={!interfaces.length} onClick={onCreate} className="button-primary"><Plus size={16} />新建工作流</button></div>
    <div className="mb-5 flex items-center gap-2 rounded-lg border border-sky-100 bg-sky-50 px-4 py-3 text-sm text-sky-800"><span className="font-semibold">接口配置</span><span>提供单次调用</span><ArrowDown size={14} className="-rotate-90" /><span className="font-semibold">接口工作流</span><span>组合调用并统一输入输出</span><ArrowDown size={14} className="-rotate-90" /><span className="font-semibold">调用服务</span><span>供机器人或其他功能引用</span></div>
    <div className="mb-4 flex items-center justify-between"><div className="relative w-80"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={keyword} onChange={(event) => { setKeyword(event.target.value); setPage(1); }} className="w-full rounded-lg border border-slate-200 bg-white py-2 pl-9 pr-3 text-sm outline-none focus:border-primary" placeholder="搜索工作流名称、描述或服务标识" /></div><span className="text-xs text-slate-400">共 {filtered.length} 个工作流</span></div>
    <div className="rounded-xl border border-slate-200 bg-white overflow-hidden"><table className="w-full text-left"><thead className="bg-slate-50 border-b"><tr><th className="px-6 py-4 text-xs text-slate-500">名称</th><th className="px-6 py-4 text-xs text-slate-500">服务标识</th><th className="px-6 py-4 text-xs text-slate-500">输入 / 输出</th><th className="px-6 py-4 text-xs text-slate-500">步骤</th><th className="px-6 py-4 text-xs text-slate-500">状态</th><th className="px-6 py-4 text-xs text-slate-500 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.length ? visible.map((item) => <WorkflowRow key={item.id} item={item} onEdit={onEdit} onCopy={onCopy} onDelete={onDelete} />) : <tr><td colSpan={6} className="px-6 py-16 text-center text-sm text-slate-400">{keyword ? '没有找到匹配的工作流' : '暂无接口工作流'}</td></tr>}</tbody></table><Pagination page={currentPage} pageCount={pageCount} onChange={setPage} /></div>
  </div>;
}

/** 渲染单条工作流信息。 */
function WorkflowRow({ item, onEdit, onCopy, onDelete }: { item: ExtractionWorkflow; onEdit: (item: ExtractionWorkflow) => void; onCopy: (item: ExtractionWorkflow) => void; onDelete: (id: string) => void }) {
  return <tr className="hover:bg-slate-50"><td className="px-6 py-4"><div className="font-semibold text-slate-800">{item.name}</div><div className="mt-1 max-w-xs truncate text-xs text-slate-400">{item.description || '-'}</div></td><td className="px-6 py-4 font-mono text-xs text-slate-600">{item.serviceKey}</td><td className="px-6 py-4 text-sm text-slate-600">{item.inputs.length} / {item.outputs.length}</td><td className="px-6 py-4 text-sm text-slate-600">{item.steps.length} 步</td><td className="px-6 py-4">{item.status === 'published' ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs text-emerald-600">可引用</span> : <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-500">草稿</span>}</td><td className="px-6 py-4"><div className="flex justify-end gap-4"><button onClick={() => onEdit(item)} className="text-sm text-primary">编辑</button><button onClick={() => onCopy(item)} className="text-sm text-primary">复制</button><button onClick={() => onDelete(item.id)} className="text-sm text-red-500">删除</button></div></td></tr>;
}

/** 配置工作流统一的输入和输出契约。 */
function ServiceContract({ workflow, onChange }: { workflow: ExtractionWorkflow; onChange: (item: ExtractionWorkflow) => void }) {
  const addField = (kind: 'inputs' | 'outputs') => onChange({ ...workflow, [kind]: [...workflow[kind], { id: `${kind}_${Date.now()}`, key: '', description: '', required: true }] });
  const updateField = (kind: 'inputs' | 'outputs', id: string, patch: Partial<WorkflowContractField>) => onChange({ ...workflow, [kind]: workflow[kind].map((item) => item.id === id ? { ...item, ...patch } : item) });
  return <section className="rounded-xl border border-slate-200 bg-white p-6"><div className="grid grid-cols-1 xl:grid-cols-3 gap-5"><Field label="工作流名称" required><input value={workflow.name} onChange={(e) => onChange({ ...workflow, name: e.target.value })} className="input-auth" placeholder="例如：创建工单并查询结果" /></Field><Field label="服务标识" required><input value={workflow.serviceKey} onChange={(e) => onChange({ ...workflow, serviceKey: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, '') })} className="input-auth" placeholder="例如：create_ticket_flow" /></Field><Field label="发布状态"><select value={workflow.status} onChange={(e) => onChange({ ...workflow, status: e.target.value as ExtractionWorkflow['status'] })} className="input-auth"><option value="draft">草稿，不可引用</option><option value="published">已发布，可引用</option></select></Field></div><Field label="描述"><input value={workflow.description} onChange={(e) => onChange({ ...workflow, description: e.target.value })} className="input-auth" /></Field><div className="mt-5 grid grid-cols-1 2xl:grid-cols-2 gap-5"><ContractFields title="服务输入" hint="调用方必须传入的参数" items={workflow.inputs} onAdd={() => addField('inputs')} onUpdate={(id, patch) => updateField('inputs', id, patch)} onDelete={(id) => onChange({ ...workflow, inputs: workflow.inputs.filter((item) => item.id !== id) })} /><ContractFields title="服务输出" hint="工作流最终返回给调用方的字段" items={workflow.outputs} steps={workflow.steps} onAdd={() => addField('outputs')} onUpdate={(id, patch) => updateField('outputs', id, patch)} onDelete={(id) => onChange({ ...workflow, outputs: workflow.outputs.filter((item) => item.id !== id) })} /></div></section>;
}

/** 编辑服务契约字段。 */
function ContractFields({ title, hint, items, steps, onAdd, onUpdate, onDelete }: { title: string; hint: string; items: WorkflowContractField[]; steps?: ExtractionWorkflowStep[]; onAdd: () => void; onUpdate: (id: string, patch: Partial<WorkflowContractField>) => void; onDelete: (id: string) => void }) {
  return <div className="rounded-lg border border-slate-200 p-4"><div className="mb-3 flex items-start justify-between"><div><div className="font-semibold text-slate-800">{title}</div><div className="text-xs text-slate-400 mt-1">{hint}</div></div><button onClick={onAdd} className="text-xs text-primary"><Plus size={14} className="inline mr-1" />添加</button></div><div className="space-y-2">{items.map((item) => <div key={item.id} className="rounded-md bg-slate-50 p-2"><div className="flex gap-2"><input value={item.key} onChange={(e) => onUpdate(item.id, { key: e.target.value })} className="w-32 rounded border border-slate-200 px-2 py-1.5 text-xs" placeholder="字段名" /><input value={item.description} onChange={(e) => onUpdate(item.id, { description: e.target.value })} className="flex-1 rounded border border-slate-200 px-2 py-1.5 text-xs" placeholder="说明" /><label className="flex items-center gap-1 whitespace-nowrap text-xs text-slate-500"><input type="checkbox" checked={item.required} onChange={(e) => onUpdate(item.id, { required: e.target.checked })} />必填</label><button onClick={() => onDelete(item.id)} className="text-slate-400 hover:text-red-500"><Trash2 size={14} /></button></div>{steps && <div className="mt-2 flex gap-2"><select value={item.sourceStepId ?? ''} onChange={(e) => onUpdate(item.id, { sourceStepId: e.target.value, sourceValue: '' })} className="w-1/2 rounded border border-slate-200 bg-white px-2 py-1.5 text-xs"><option value="">选择来源步骤</option>{steps.map((step) => <option key={step.id} value={step.id}>{step.name}</option>)}</select><select value={item.sourceValue ?? ''} onChange={(e) => onUpdate(item.id, { sourceValue: e.target.value })} className="w-1/2 rounded border border-slate-200 bg-white px-2 py-1.5 text-xs"><option value="">选择步骤输出</option>{steps.find((step) => step.id === item.sourceStepId)?.outputMappings.map((output) => <option key={output.id} value={output.outputKey}>{output.outputKey}</option>)}</select></div>}</div>)}</div></div>;
}

/** 编辑单个顺序调用步骤。 */
function StepEditor({ step, stepIndex, allSteps, interfaces, onChange, onMove, onDelete }: { step: ExtractionWorkflowStep; stepIndex: number; allSteps: ExtractionWorkflowStep[]; interfaces: ExtractionConfig[]; onChange: (step: ExtractionWorkflowStep) => void; onMove: (direction: -1 | 1) => void; onDelete: () => void }) {
  const currentInterface = interfaces.find((item) => item.id === step.interfaceId);
  const addInput = () => onChange({ ...step, inputMappings: [...step.inputMappings, { id: `input_${Date.now()}`, targetKey: '', source: stepIndex === 0 ? 'workflow_input' : 'step_output', sourceValue: '', sourceStepId: stepIndex > 0 ? allSteps[stepIndex - 1]?.id : undefined }] });
  const addOutput = () => onChange({ ...step, outputMappings: [...step.outputMappings, { id: `output_${Date.now()}`, outputKey: '', sourcePath: '' }] });
  const updateInput = (id: string, patch: Partial<WorkflowInputMapping>) => onChange({ ...step, inputMappings: step.inputMappings.map((item) => item.id === id ? { ...item, ...patch } : item) });
  const updateOutput = (id: string, patch: Partial<WorkflowOutputMapping>) => onChange({ ...step, outputMappings: step.outputMappings.map((item) => item.id === id ? { ...item, ...patch } : item) });
  return <div><div className="flex items-center justify-between mb-5"><div><h2 className="font-bold text-slate-900">步骤 {stepIndex + 1} 设置</h2><p className="mt-1 text-xs text-slate-400">配置本步骤调用接口时的数据来源，以及提供给后续步骤的数据。</p></div><div className="flex gap-1"><button onClick={() => onMove(-1)} className="icon-button"><ArrowUp size={16} /></button><button onClick={() => onMove(1)} className="icon-button"><ArrowDown size={16} /></button><button onClick={onDelete} className="icon-button hover:text-red-500"><Trash2 size={16} /></button></div></div><div className="grid grid-cols-2 gap-5"><Field label="步骤名称"><input value={step.name} onChange={(e) => onChange({ ...step, name: e.target.value })} className="input-auth" /></Field><Field label="调用接口"><select value={step.interfaceId} onChange={(e) => onChange({ ...step, interfaceId: e.target.value, inputMappings: [], outputMappings: [] })} className="input-auth"><option value="">请选择接口</option>{interfaces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>
    <MappingSection title="输入映射" hint="目标接口参数 ← 工作流输入、前序步骤输出或固定值" onAdd={addInput}>{step.inputMappings.map((mapping) => <div key={mapping.id} className="grid grid-cols-[1fr_1fr_1.3fr_auto] gap-2"><select value={mapping.targetKey} onChange={(e) => updateInput(mapping.id, { targetKey: e.target.value })} className="map-field"><option value="">目标接口参数</option>{currentInterface?.params.map((param) => <option key={param.id} value={param.key}>{param.key}</option>)}</select><select value={mapping.source} onChange={(e) => updateInput(mapping.id, { source: e.target.value as WorkflowInputMapping['source'], sourceValue: '', sourceStepId: undefined })} className="map-field"><option value="workflow_input">工作流输入</option>{stepIndex > 0 && <option value="step_output">前序步骤输出</option>}<option value="constant">固定值</option></select><SourceSelector mapping={mapping} earlierSteps={allSteps.slice(0, stepIndex)} onChange={(patch) => updateInput(mapping.id, patch)} /><button onClick={() => onChange({ ...step, inputMappings: step.inputMappings.filter((item) => item.id !== mapping.id) })} className="text-slate-400 hover:text-red-500"><Trash2 size={14} /></button></div>)}</MappingSection>
    <MappingSection title="步骤输出" hint="步骤输出名称 ← 接口返回字段，供后续步骤和服务输出引用" onAdd={addOutput}>{step.outputMappings.map((mapping) => <div key={mapping.id} className="grid grid-cols-[1fr_1fr_auto] gap-2"><select value={mapping.sourcePath} onChange={(e) => updateOutput(mapping.id, { sourcePath: e.target.value })} className="map-field"><option value="">接口返回字段</option>{currentInterface?.responseMapping.map((item) => <option key={item.key} value={item.key}>{item.key} · {item.path}</option>)}</select><input value={mapping.outputKey} onChange={(e) => updateOutput(mapping.id, { outputKey: e.target.value })} className="map-field" placeholder="步骤输出名称" /><button onClick={() => onChange({ ...step, outputMappings: step.outputMappings.filter((item) => item.id !== mapping.id) })} className="text-slate-400 hover:text-red-500"><Trash2 size={14} /></button></div>)}</MappingSection>
    <div className="mt-6 border-t pt-5"><div className="grid grid-cols-3 gap-4"><Field label="超时时间（秒）"><input type="number" min={1} max={60} value={step.timeoutSeconds} onChange={(e) => onChange({ ...step, timeoutSeconds: Math.max(1, Math.min(60, Number(e.target.value))) })} className="input-auth" /></Field><Field label="失败处理"><select value={step.failureAction} onChange={(e) => onChange({ ...step, failureAction: e.target.value as ExtractionWorkflowStep['failureAction'], retryCount: e.target.value === 'retry' ? 1 : 0 })} className="input-auth"><option value="stop">停止工作流并返回失败</option><option value="retry">重试当前步骤</option><option value="skip">跳过并继续</option></select></Field>{step.failureAction === 'retry' && <Field label="重试次数"><select value={step.retryCount} onChange={(e) => onChange({ ...step, retryCount: Number(e.target.value) as 1 | 2 | 3 })} className="input-auth"><option value={1}>1 次</option><option value={2}>2 次</option><option value={3}>3 次</option></select></Field>}</div><p className="mt-3 text-xs text-slate-400">接口超时、非成功状态码或必需输出缺失时执行失败策略；输出被后续步骤使用时不能跳过。</p></div>
  </div>;
}

/** 选择映射来源。 */
function SourceSelector({ mapping, earlierSteps, onChange }: { mapping: WorkflowInputMapping; earlierSteps: ExtractionWorkflowStep[]; onChange: (patch: Partial<WorkflowInputMapping>) => void }) {
  if (mapping.source === 'step_output') return <div className="flex gap-2"><select value={mapping.sourceStepId ?? ''} onChange={(e) => onChange({ sourceStepId: e.target.value, sourceValue: '' })} className="map-field"><option value="">来源步骤</option>{earlierSteps.map((step) => <option key={step.id} value={step.id}>{step.name}</option>)}</select><select value={mapping.sourceValue} onChange={(e) => onChange({ sourceValue: e.target.value })} className="map-field"><option value="">输出字段</option>{earlierSteps.find((step) => step.id === mapping.sourceStepId)?.outputMappings.map((output) => <option key={output.id} value={output.outputKey}>{output.outputKey}</option>)}</select></div>;
  return <input value={mapping.sourceValue} onChange={(e) => onChange({ sourceValue: e.target.value })} className="map-field" placeholder={mapping.source === 'workflow_input' ? '工作流输入字段' : '固定值'} />;
}

const MappingSection = ({ title, hint, onAdd, children }: { title: string; hint: string; onAdd: () => void; children: React.ReactNode }) => <div className="mt-6 rounded-lg border border-slate-200 p-4"><div className="mb-3 flex justify-between"><div><div className="flex items-center font-semibold text-slate-800"><Braces size={16} className="mr-2 text-primary" />{title}</div><div className="mt-1 text-xs text-slate-400">{hint}</div></div><button onClick={onAdd} className="text-xs text-primary"><Plus size={14} className="inline mr-1" />添加映射</button></div><div className="space-y-2">{children}</div></div>;
const Field = ({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) => <label className="block text-sm text-slate-600">{required && <span className="text-red-500 mr-1">*</span>}{label}<div className="mt-2">{children}</div></label>;
const Pagination = ({ page, pageCount, onChange }: { page: number; pageCount: number; onChange: (page: number) => void }) => <div className="flex items-center justify-between border-t px-6 py-3 text-sm"><span className="text-slate-400">第 {page} / {pageCount} 页</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => onChange(page - 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">上一页</button><button disabled={page === pageCount} onClick={() => onChange(page + 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">下一页</button></div></div>;
